src/Form/DeleteAchievementsForm.php
<?php

namespace Drupal\opigno_learning_path\Form;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\Core\Database\Connection;
use Drupal\Core\Form\ConfirmFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\Group;
use Drupal\opigno_module\Entity\OpignoModule;
use Drupal\opigno_module\Entity\UserModuleStatus;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class LearningPathAdminSettingsForm.
 */
class DeleteAchievementsForm extends ConfirmFormBase {

  /**
   * Group.
   *
   * @var \Drupal\group\Entity\Group
   */
  protected $group;

  /**
   * Database connection.
   *
   * @var \Drupal\Core\Database\Connection
   */
  protected $database;

  /**
   * DeleteAchievementsForm constructor.
   */
  public function __construct(Connection $database) {
    $this->database = $database;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static($container->get('database'));
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'opigno_learning_path_delete_achievements';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, $group = NULL) {
    $form = parent::buildForm($form, $form_state);

    if (isset($group)) {
      $this->group = $group;
      $form['group'] = [
        '#type' => 'hidden',
        '#value' => $group->id(),
      ];
    }

    $form['actions']['submit']['#name'] = 'submit';

    $form['actions']['cancel']['#type'] = 'submit';
    $form['actions']['cancel']['#name'] = 'cancel';
    $form['actions']['cancel']['#value'] = $this->getCancelText();

    $is_ajax = $this->getRequest()->isXmlHttpRequest();
    if ($is_ajax) {
      $form['actions']['cancel']['#ajax'] = [
        'callback' => [$this, 'closeModal'],
        'event' => 'click',
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function getQuestion() {
    return '';
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription() {
    return $this->t('The contents of that training has changed. If you start again that training, your previous achievements for it will be deleted. Do you want to continue?');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelUrl() {
    if (isset($this->group)) {
      return $this->group->toUrl();
    }
    else {
      return Url::fromRoute('<front>');
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getConfirmText() {
    return $this->t('Yes');
  }

  /**
   * {@inheritdoc}
   */
  public function getCancelText() {
    return $this->t('No');
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $element = $form_state->getTriggeringElement();
    if (isset($element['#name'])) {
      if ($element['#name'] === 'submit') {
        $uid = $this->currentUser()->id();
        $gid = $form_state->getValue('group');
        if (isset($gid)) {
          $this->database
            ->delete('opigno_learning_path_step_achievements')
            ->condition('uid', $uid)
            ->condition('gid', $gid)
            ->execute();

          $this->database
            ->delete('opigno_learning_path_achievements')
            ->condition('uid', $uid)
            ->condition('gid', $gid)
            ->execute();

          $group = Group::load($gid);
          if (isset($group)) {
            // Load modules of a LP group.
            $modules = $group->getContentEntities('opigno_module_group');
            // Delete all answers connected to this user and LP.
            $this->deleteAnswers((int) $group->id(), $uid, $modules);
            $module = reset($modules);
            if (!empty($module)) {
              // Create new unfinished user module attempt on the first module
              // of training to disable the training resume.
              $attempt = UserModuleStatus::create([]);
              $attempt->setModule($module);
              $attempt->setFinished(0);
              $attempt->save();
            }
          }

          $form_state->setRedirect('opigno_learning_path.steps.start', [
            'group' => $gid,
          ]);
        }
      }
      elseif ($element['#name'] === 'cancel') {
        $form_state->setRedirectUrl($this->getCancelUrl());
      }
    }
  }

  /**
   * Delete answers.
   */
  private function deleteAnswers(int $group_id, int $uid, array $modules) {
    foreach ($modules as $module) {
      if (!$module instanceof OpignoModule) {
        continue;
      }
      $user_module_statuses = \Drupal::entityTypeManager()->getStorage('user_module_status')->loadByProperties(
        [
          'learning_path' => $group_id,
          'user_id' => $uid,
          'module' => $module->id(),
        ]
      );
      foreach ($user_module_statuses as $status) {
        if (!$status instanceof UserModuleStatus) {
          continue;
        }
        $answers = $status->getAnswers();
        foreach ($answers as $answer) {
          $answer->delete();
        }
      }
    }
  }

  /**
   * Returns ajax response.
   */
  public function closeModal(array &$form, FormStateInterface $form_state) {
    $response = new AjaxResponse();
    $response->addCommand(new CloseModalDialogCommand());
    return $response;
  }

}

templates/group--learning-path--teaser-of-group.html.twig
{#
/**
 * @file
 * Default theme implementation to display a group.
 *
 * Available variables:
 * - group: The group entity with limited access to object properties and
 *   methods. Only "getter" methods (method names starting with "get", "has",
 *   or "is") and a few common methods such as "id" and "label" are available.
 *   Calling other methods (such as group.delete) will result in an exception.
 * - label: The title of the group.
 * - content: All group items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.field_example }}. Use
 *   {{ content|without('field_example') }} to temporarily suppress the
 *   printing of a given child element.
 * - url: Direct URL of the current group.
 * - attributes: HTML attributes for the containing element.
 *   The attributes.class element may contain one or more of the following
 *   classes:
 *   - group: The current template type (also known as a "theming hook").
 *   - group--[type]: The current group type. For example, if the group is a
 *     "Classroom" it would result in "group--classroom". Note that the machine
 *     name will often be in a short form of the human readable label.
 *   - group--[view_mode]: The View Mode of the group; for example, a
 *     teaser would result in: "group--teaser", and full: "group--full".
 * - title_attributes: Same as attributes, except applied to the main title
 *   tag that appears in the template.
 * - content_attributes: Same as attributes, except applied to the main
 *   content tag that appears in the template.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 * - view_mode: View mode; for example, "teaser" or "full".
 * - page: Flag for the full page state. Will be true if view_mode is 'full'.
 *
 * @see template_preprocess_group()
 *
 * @ingroup themeable
 */
#}
<div{{ attributes.addclass('group-opigno-course') }}>
  {{ title_prefix }}
  {% if not page %}
    <h3{{ title_attributes }}>
      <a href="{{ url }}" rel="bookmark">{{ label }}</a>
    </h3>
  {% endif %}
  {{ title_suffix }}
  <div class="row">
    <div id="group-content" {{ content_attributes.addClass('col-md-8') }}>
        <div class="bg-white px-3 py-3">
            {{ content.field_learning_path_description }}
        </div>
    </div>
  </div>
</div>

templates/group--learning-path.html.twig
{#
/**
 * @file
 * Default theme implementation to display a group.
 *
 * Available variables:
 * - group: The group entity with limited access to object properties and
 *   methods. Only "getter" methods (method names starting with "get", "has",
 *   or "is") and a few common methods such as "id" and "label" are available.
 *   Calling other methods (such as group.delete) will result in an exception.
 * - label: The title of the group.
 * - content: All group items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.field_example }}. Use
 *   {{ content|without('field_example') }} to temporarily suppress the
 *   printing of a given child element.
 * - url: Direct URL of the current group.
 * - attributes: HTML attributes for the containing element.
 *   The attributes.class element may contain one or more of the following
 *   classes:
 *   - group: The current template type (also known as a "theming hook").
 *   - group--[type]: The current group type. For example, if the group is a
 *     "Classroom" it would result in "group--classroom". Note that the machine
 *     name will often be in a short form of the human readable label.
 *   - group--[view_mode]: The View Mode of the group; for example, a
 *     teaser would result in: "group--teaser", and full: "group--full".
 * - title_attributes: Same as attributes, except applied to the main title
 *   tag that appears in the template.
 * - content_attributes: Same as attributes, except applied to the main
 *   content tag that appears in the template.
 * - title_prefix: Additional output populated by modules, intended to be
 *   displayed in front of the main title tag that appears in the template.
 * - title_suffix: Additional output populated by modules, intended to be
 *   displayed after the main title tag that appears in the template.
 * - view_mode: View mode; for example, "teaser" or "full".
 * - page: Flag for the full page state. Will be true if view_mode is 'full'.
 *
 * @see template_preprocess_group()
 *
 * @ingroup themeable
 */
#}

<div{{ attributes.addclass('group-opigno-course') }}>

  {{ title_prefix }}
  {% if not page %}
    <h2{{ title_attributes }}>
      <a href="{{ url }}" rel="bookmark">{{ label }}</a>
    </h2>
  {% endif %}
  {{ title_suffix }}
  <div class="row">
    {% if opigno_catalog_is_member(group.id()) %}
      {{ get_progress() }}
    {% endif %}
    <div class="col-md-4">
      <section>
        <h2 class="h4 bg-primary color-white text-uppercase mb-0 px-3 py-2">{{ 'Information'|t }}</h2>
        <div class="content bg-light px-3 pl-md-0 py-2">
          <div class="lp-image">
            {% if content.field_learning_path_media_image[0] %}
              {{ content.field_learning_path_media_image }}
            {% else %}
              {{ opigno_catalog_get_default_image('learning_path', label) }}
            {% endif %}
          </div>
          <div class="duration d-flex px-2 py-2 bg-white mt-2">
            <i class="icon-duration"></i>
            <div class="label">{{ 'Length'|t }}</div>
            <div class="value text-right ml-auto">{{ group.field_learning_path_duration.value }}</div>
          </div>
          <div class="category d-flex px-2 py-2 bg-white mt-2">
            <i class="icon-category"></i>
            <div class="label">{{ 'Subject'|t }}</div>
            <div class="value text-right ml-auto">{{ learning_path_category }}</div>
          </div>
        </div>
        {{ get_join_group_link(null, null, {'class': ['opigno-quiz-app-course-button', 'bg-success', 'color-white', 'd-block', 'px-2', 'py-2', 'text-center', 'text-uppercase', 'join-link']}) }}
      </section>
    </div>
    <div id="group-content" {{ content_attributes.addClass('col-md-8') }}>
      <h2 class="h4 bg-primary text-uppercase color-white mb-0 px-3 py-2">{{ 'About this training'|t }}</h2>
      <div class="content bg-light px-3 px-md-2 pt-2">
        <div class="bg-white px-3 py-3">
          {{ content|without('field_learning_path_media_image', 'field_learning_path_duration', 'field_learning_path_category') }}
        </div>
      </div>
      {{ get_start_link(null, {'class': ['opigno-quiz-app-course-button', 'bg-success', 'color-white', 'd-block', 'px-2', 'py-2', 'text-center', 'text-uppercase']}) }}
    </div>
    {{ get_training_content() }}
  </div>
</div>

templates/opigno-learning-path-courses.html.twig
<!-- group/{group}/inner-courses -->

<base href="{{ base_path ~ base_href }}">

<script type="text/javascript">
  window.appConfig = {
    formSubmitBtn: false,
    groupId: {{ learning_path_id }},
    groupType: '{{ group_type }}',
    apiBaseUrl: '{{ base_path }}',
    viewType: '{{ view_type }}',
    userHasInfoCard: '{{ user_has_info_card }}',
    hideInfocardUrl: '/opigno-group-manager/hide-info-card',
    getCourses: '/group/%groupId/courses/get-items',
    getEntitiesUrl: '/group/%groupId/get-items',
    getEntitiesPositionsUrl: '/group/%groupId/get-positions',
    setEntitiesPositionsUrl: '/group/%groupId/set-positions',
    getEntitiesTypesUrl: '/group/%groupId/get-item-types',
    getEntitiesAvailableUrl: '/group/%groupId/get-available-items',
    getEntityFormUrl: '/group/%groupId/item-form/%bundle/%entityId{{ parent_learning_path }}',
    getActivitiesUrl: '/group/%moduleId/get-activities',
    getGuidedNavigationUrl: '/group/%groupId/get-guided-navigation',
    getRequiredActivitiesUrl: '/group/%contentType/%entityId/get-activities-required',
    submitAddEntityFormUrl: '/group/%groupId/create-item/%bundle',
    addEntityUrl: '/group/%groupId/add-item',
    removeEntityUrl: '/group/%groupId/remove-item',
    addEntityLinkUrl: '/group/%groupId/add-link',
    updateEntityLinkUrl: '/group/%groupId/update-link',
    removeEntityLinkUrl: '/group/%groupId/remove-link',
    updateEntityMandatoryUrl: '/group/%groupId/update-mandatory',
    updateEntityMinScoreUrl: '/group/%groupId/update-min-score',
    updateEntitiesUrl: '/group/%groupId/update-entities',
    updateGuidedNavigationUrl: '/group/%groupId/update-guided-navigation',
    activitiesPageUrl: '/group/%groupId/inner-modules',
    text_add_your_first_item: '{{ "Add your first item"|t|e }}',
    text_guided_navigation: '{{ "Guided navigation"|t|e }}',
    text_free_navigation: '{{ "Free navigation"|t|e }}',
    text_if_entity_dropped_under_children: '{{ "Cannot drop under or at the same level as children, move children before"|t|e }}',
    text_cannot_drop_over_or_at_the_same_level: '{{ "Cannot drop over or at the same level as parent"|t|e }}',
    text_click_now_on_the_two_steps_of_your_training: '{{ "Click now on the two steps of your training to be linked in order to create the link"|t|e }}',
    text_status_message: '{{ "Status message"|t|e }}',
    text_conditions: '{{ "Conditions"|t|e }}',
    text_edit: '{{ "edit"|t|e }}',
    text_last_step: '{{ "Last step:"|t|e }}',
    text_validate: '{{ "Validate"|t|e }}',
    text_cancel: '{{ "cancel"|t|e }}',
    text_delete_link: '{{ "delete link"|t|e }}',
    text_this_action_create_an_orphan: '{{ "This action create an orphan, confirm:"|t|e }}',
    text_confirm: '{{ "confirm"|t|e }}',
    bt_add_a_link: '{{ "add a link"|t|e }}',
    nextLink: '{{ next_link }}',
    text_opigno_module: '{{ "Opigno module"|t|e }}',
    text_course: '{{ "Course"|t|e }}',
    text_create_a_new: '{{ "Create a new"|t|e }}',
    text_or_add_from_existing_catalogue: '{{ "Or add from the existing catalog"|t|e }}',
    text_live_meeting: '{{ "Live meeting"|t|e }}',
    text_instructor_led_training: '{{ "Instructor-Led Training"|t|e }}',
    text_close: '{{ "close"|t|e }}',
    text_add_a_new_item: '{{ "Click here to add a new item"|t|e }}',
    text_do_not_show_this_message_again: '{{ "Do not show this message again"|t|e }}',
    text_modules: '{{ "modules"|t|e }}',
    text_module: '{{ "module"|t|e }}',
    text_add: '{{ "add"|t|e }}',
    text_update: '{{ "update"|t|e }}',
    text_score: '{{ "score"|t|e }}',
    text_delete: '{{ "delete"|t|e }}',
    text_mandatory: '{{ "Mandatory"|t|e }}',
    text_minimum_score_to_validate_step: '{{ "Minimum score to validate step"|t|e }}',
    text_search: '{{ "Search"|t|e }}',
    text_score_2: '{{ "Score"|t|e }}',
    text_answer_at_last_step: '{{ "Answer at last step"|t|e }}',
    text_tree_view: '{{ "Tree view"|t|e }}'
  };
</script>

<app-root class="d-block">{{ 'Loading app...'|t|e }}</app-root>

templates/opigno-learning-path-item-form.html.twig
{{ page.content|raw }}

templates/opigno-learning-path-modules.html.twig
<!-- group/{group}/inner-modules -->

<base href="{{ base_path ~ base_href }}">

<script type="text/javascript">
  window.appConfig = {
    formSubmitBtn: false,
    groupId: {{ learning_path_id }},
    apiBaseUrl: '{{ base_path }}',
    moduleContext: {{ module_context }},
    text_all: '{{ "All"|t|e }}',
    text_activities_bank: '{{ "Activities bank"|t|e }}',
    text_add_activity: '{{ "Add activity"|t|e }}',
    text_activity: '{{ "activity"|t|e }}',
    text_activities: '{{ "activities"|t|e }}',
    text_show_activities: '{{ "Show activities"|t|e }}',
    text_add_activities_to_the_module: '{{ "Add activities to the module"|t|e }}',
    text_close: '{{ "close"|t|e }}',
    text_move: '{{ "move"|t|e }}',
    text_preview: '{{ "Preview"|t|e }}',
    text_max_score: '{{ "max score"|t|e }}',
    text_edit: '{{ "edit"|t|e }}',
    text_delete: '{{ "delete"|t|e }}',
    text_choose_an_activity_type: '{{ "CHOOSE AN ACTIVITY TYPE"|t|e }}',
    text_choose_an_activity: '{{ "CHOOSE AN ACTIVITY"|t|e }}',
    text_help: '{{ "help"|t|e }}',
    text_create_a_new_activity: '{{ "Create a new activity"|t|e }}',
    text_or_add_from_existing_catalogue: '{{ "Or add from the existing catalog"|t|e }}',
    text_search_for_an_activity: '{{ "Search for an activity"|t|e }}',
    text_activity_id_table: '{{ "Activity ID"|t|e }}',
    text_max_score_table: '{{ "Max score"|t|e }}',
    text_edit_table: '{{ "Edit"|t|e }}',
    text_remove_table: '{{ "Remove"|t|e }}',
    text_confirm_delete: '{{ "Confirm delete"|t|e }}',
    text_cancel: '{{ "cancel"|t|e }}',
    text_confirm: '{{ "confirm"|t|e }}',
    text_preview_of_activity: '{{ "Preview of activity"|t|e }}',
    text_property_of: '{{ "Property of"|t|e }}',
    text_add_a_step: '{{ "ADD A STEP"|t|e }}',
    text_add_a: '{{ "ADD A"|t|e }}',
    text_create_a_new: '{{ "Create a new"|t|e }}',
    text_module: '{{ "module"|t|e }}',
    text_modules: '{{ "modules"|t|e }}',
    text_tree_view: '{{ "Tree view"|t|e }}',
    text_score: '{{ "Score"|t|e }}',
    text_search: '{{ "Search"|t|e }}',
    viewType: 'activities',
    userHasInfoCard: '{{ user_has_info_card }}',
    hideInfocardUrl: '/opigno-group-manager/hide-info-card',
    getEntitiesUrl: '/group/%groupId/get-items',
    getEntitiesPositionsUrl: '/group/%groupId/get-positions',
    getModulesUrl: '/group/%groupId/modules/get-items',
    getActivitiesUrl: '/group/%moduleId/get-activities',
    getExtPackageFormUrl: '/module/%opigno_module/add-external-package',
    getExtPackagePptFormUrl: '/module/%opigno_module/add-external-package/ppt',
    updateActivityUrl: '/group/%moduleId/update-activity',
    deleteActivityUrl: '/group/%moduleId/delete-activity',
    getActivityTypesUrl: '/module/manager/get-activity-types',
    getActivityFormUrl: '/module/%opigno_module/item-form/%type/%item',
    getActivityPreviewUrl: '/module/manager/activity-preview/%opigno_activity',
    getActivityListUrl: '/module/%opigno_module/manager/get-activities-list',
    addActivityUrl: '/module/%opigno_module/add-activity/%opigno_activity/group/%group_id',
    addActivitiesBankUrl: '/opigno_module/%opigno_module/activities-bank-lpm',
    updateWeightUrl: '/module/manager/update-weight',
    nextLink: '{{ next_link }}',
    text_score_2: '{{ "Score"|t|e }}',
    text_answer_at_last_step: '{{ "Answer at last step"|t|e }}',
  };
</script>

<app-root class="d-block">{{ 'Loading app...'|t|e }}</app-root>

templates/opigno-learning-path-step-block.html.twig
<div>
  <div class="lp_steps_block_summary">
    <span class="{{ state_summary.class }}"></span>
    <h3 class="lp_steps_block_summary_title">{{ state_summary.title }}</h3>
    <p class="lp_steps_block_summary_score">{{ state_summary.score }}</p>
    <p class="lp_steps_block_summary_progress">{{ state_summary.progress }}</p>
  </div>

  <h3 class="lp_steps_block_title">{{ title }}</h3>

  <div class="tableresponsive-toggle-columns">
    <button type="button" class="link tableresponsive-toggle"
      title="Show table cells that were hidden to make the table fit within a small screen."
      style="display: none;">
      {{ 'Hide lower priority columns'|t }}
    </button>
  </div>

  {{ table_summary }}

  <table class="lp_steps_block_table responsive-enabled table table-hover" data-striping="1">

    <thead>
      <tr>
        {% for header in table_summary.headers %}
        <th>{{ header }}</th>
        {% endfor %}
      </tr>
    </thead>

    <tbody>
      {% for row in table_summary.data %}
      <tr>
        <td>{{ row.name }}</td>
        <td>
          {% if row.score %}
            <span class="lp_steps_block_score">{{ row.score }}</span>
          {% else %}
            -
          {% endif %}
        </td>
        <td>
          {% if row.state %}
          <span class="{{ row.state }}"></span>
          {% else %}
          -
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

templates/opigno-learning-path-training-content-step.html.twig
{#
/**
 * @file
 * Default theme implementation to display the training content step.
 *
 * Available variables:
 * - step: The step object with all the data.
 * - group: The Group object which the steps is part of.
 */
#}
<div class="lp_step">
  <div class="lp_step_title_wrapper">
    {% if step.mandatory %}
      <span class="lp_step_required"></span>
    {% endif %}
    <h3 class="lp_step_title">{{ step.name }}</h3>
  </div>
  {% if step.typology == 'Course' %}
    {% for course_step in step.course_steps %}
      <div class="lp_step_content">
        <div class="lp_step_summary">
          <div class="lp_step_summary_title_wrapper">
            <h3 class="lp_step_summary_title">{{ course_step.title }}</h3>

            {% if course_step.sub_title %}
              <h4 class="lp_step_summary_subtitle">{{ course_step.sub_title }}</h4>
            {% endif %}

            {% if course_step.description %}
              <div class="lp_step_summary_description">{{ course_step.description|raw }}</div>
            {% endif %}
          </div>
          {{ course_step.summary_details_table }}
        </div>
      </div>
    {% endfor %}
  {% else %}
    <div class="lp_step_content">
      <div class="lp_step_summary">
        <div class="lp_step_summary_title_wrapper">
          <h3 class="lp_step_summary_title">{{ step.title }}</h3>

          {% if step.sub_title %}
            <h4 class="lp_step_summary_subtitle">{{ step.sub_title }}</h4>
          {% endif %}

          {% if step.description %}
            <div class="lp_step_summary_description">{{ step.description|raw }}</div>
          {% endif %}
        </div>
        {{ step.summary_details_table }}
      </div>
    </div>
  {% endif %}
</div>

templates/opigno-learning-path-training-content.html.twig
{#
/**
 * @file
 * Default theme implementation to display the training content.
 *
 * Available variables:
 * - content: All training content items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.tabs }}. Use
 *   {{ content|without('tabs') }} to temporarily suppress the
 *   printing of a given child element.
 */
#}
<div id="training-content-wrapper" class="col-12">
  {{ content }}
</div>

templates/opigno-learning-path-training-course-content.html.twig
{#
/**
 * @file
 * Default theme implementation to display the training elements.
 *
 * Available variables:
 * - #course_id: Course id.
 * - elements: The training elements.
 */
#}

<div id="{{ 'course_steps_' ~ elements['#course_id'] }}"
     class="lp_course_steps_wrapper ml-md-7 mr-md-5 mb-5">
  <h4>{{ 'Course Content'|t }}</h4>
  {{ elements }}
</div>

templates/opigno-learning-path-training-module.html.twig
{#
/**
 * @file
 * Default theme implementation to display learnign path module.
 *
 * - status
 * - group_id
 * - step
 * - approved
 * - completed
 * - badges
 * - time_spent
 */
#}

{% set process = (100 * step.progress)|round() %}

<div class="lp_step_summary_wrapper">
  <div class="lp_step_summary px-3">
    <div class="row">
      <div class="col-lg-4 col-md-2 d-sm-flex d-md-block d-lg-flex align-items-center mb-4 mb-md-0 col-step-item">
        <div class="lp_step_summary_title h4 mb-0 mb-md-3 mb-lg-0 text-uppercase lp-step-title">{{ status.title }}</div>
        <div class="lp_step_summary_icon ml-3 ml-md-0 ml-lg-3 lp-step-icon {{ status.class }}"></div>
      </div>
      <div class="col-lg-4 col-md-5 mb-4 mb-md-0 col-step-item">
        <div class="ml-0 ml-md-5 mr-3 pull-left lp-step-title">
          <div class="h4 color-blue mb-0">{{ process ~ '%' }}</div>
          <div>{{ 'Completion'|t }}</div>
        </div>
        <div class="lp_step_summary_completion_chart donut-wrapper ml-3 lp-step-icon">
          <canvas class="donut"
                  data-value="{{ process }}"
                  data-width="7"
                  data-color="#5bb4d8"
                  data-track-color="#fff"
                  width="67"
                  height="67"
                  style="box-shadow: rgb(255, 255, 255) 0 0 0 3.5px inset;">
          </canvas>
        </div>
      </div>
      <div class="col-lg-4 col-md-5 col-step-item">
        <div class="ml-0 ml-md-5 lp_step_summary_approved mr-3 pull-left lp-step-title">
          <div class="h4 color-blue mb-0">{{ approved.value }}</div>
          <div>
            {{ 'Activities'|t }}<br>
            {{ 'done'|t }}
          </div>
        </div>
        <div class="lp_step_summary_approved_chart donut-wrapper ml-3 mr-auto lp-step-icon">
          <canvas class="donut"
                  data-value="{{ approved_percent }}"
                  data-width="7"
                  data-color="#5bb4d8"
                  data-track-color="#fff"
                  width="67"
                  height="67"
                  style="box-shadow: rgb(255, 255, 255) 0 0 0 3.5px inset;">
          </canvas>
        </div>
      </div>
    </div>
    <div class="w-100 mt-4 d-flex justify-content-center">
      <div>
        <div class="text-italic">{{ 'Time spent'|t }}</div>
        <div class="color-blue h5">{{ time_spent }}</div>
      </div>
      <div class="ml-3 ml-md-5">
        <div class="text-italic">{{ 'Completed on'|t }}</div>
        <div class="color-blue h5">{{ completed }}</div>
      </div>
      <div class="ml-3 ml-md-5">
        <div class="text-italic">{{ 'Badges earned'|t }}</div>
        <div class="color-blue h5">{{ badges }}</div>
       </div>
    </div>
  </div>
  <div class="lp_step_summary_clickable"
       data-training="{{ group_id }}"
       data-module="{{ step.id }}">
    {{ 'more details'|t }}
  </div>
  <div id="{{ 'module_panel_' ~ group_id ~ '_' ~ step.id }}" class="lp_module_panel"></div>
</div>